project_id = "voka"

[auth]
enable_anonymous_sign_ins = true
additional_redirect_urls = ["voka://auth?mode=confirmed", "voka://auth?mode=reset"]
minimum_password_length = 15
password_requirements = ""

[functions.realtime-session]
verify_jwt = true

[functions.delete-account]
verify_jwt = true
